import "package:flutter/material.dart";

class AppTheme {
  final TextTheme textTheme;

  const AppTheme(this.textTheme);

  static ThemeData light() {
    return ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xff476730),
          surfaceTint: Color(0xff476730),
          onPrimary: Color(0xffffffff),
          primaryContainer: Color(0xffc7eea9),
          onPrimaryContainer: Color(0xff0a2000),
          secondary: Color(0xff56624b),
          onSecondary: Color(0xffffffff),
          secondaryContainer: Color(0xffd9e7ca),
          onSecondaryContainer: Color(0xff141e0c),
          tertiary: Color(0xff386665),
          onTertiary: Color(0xffffffff),
          tertiaryContainer: Color(0xffbbecea),
          onTertiaryContainer: Color(0xff002020),
          error: Color(0xffba1a1a),
          onError: Color(0xffffffff),
          errorContainer: Color(0xffffdad6),
          onErrorContainer: Color(0xff410002),
          surface: Color(0xfff9faf0),
          onSurface: Color(0xff191d16),
          onSurfaceVariant: Color(0xff44483e),
          outline: Color(0xff74796d),
          outlineVariant: Color(0xffc4c8bb),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xff2e312a),
          // inverseOnSurface: Color(4293980903),
          inversePrimary: Color(0xffacd28f),
          primaryFixed: Color(0xffc7eea9),
          onPrimaryFixed: Color(0xff0a2000),
          primaryFixedDim: Color(0xffacd28f),
          onPrimaryFixedVariant: Color(0xff304f1a),
          secondaryFixed: Color(0xffd9e7ca),
          onSecondaryFixed: Color(0xff141e0c),
          secondaryFixedDim: Color(0xffbdcbaf),
          onSecondaryFixedVariant: Color(0xff3f4a35),
          tertiaryFixed: Color(0xffbbecea),
          onTertiaryFixed: Color(0xff002020),
          tertiaryFixedDim: Color(0xffa0cfce),
          onTertiaryFixedVariant: Color(0xff1e4e4d),
          surfaceDim: Color(0xffd9dbd1),
          surfaceBright: Color(0xfff9faf0),
          surfaceContainerLowest: Color(0xffffffff),
          surfaceContainerLow: Color(0xfff3f5ea),
          surfaceContainer: Color(0xffedefe4),
          surfaceContainerHigh: Color(0xffe7e9df),
          surfaceContainerHighest: Color(0xffe1e4d9),
        ));
  }

  static ThemeData lightMediumContrast() {
    return ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xff2c4b17),
          surfaceTint: Color(0xff476730),
          onPrimary: Color(0xffffffff),
          primaryContainer: Color(0xff5c7e44),
          onPrimaryContainer: Color(0xffffffff),
          secondary: Color(0xff3b4631),
          onSecondary: Color(0xffffffff),
          secondaryContainer: Color(0xff6c7960),
          onSecondaryContainer: Color(0xffffffff),
          tertiary: Color(0xff194a49),
          onTertiary: Color(0xffffffff),
          tertiaryContainer: Color(0xff4f7c7c),
          onTertiaryContainer: Color(0xffffffff),
          error: Color(0xff8c0009),
          onError: Color(0xffffffff),
          errorContainer: Color(0xffda342e),
          onErrorContainer: Color(0xffffffff),
          surface: Color(0xfff9faf0),
          onSurface: Color(0xff191d16),
          onSurfaceVariant: Color(0xff40443a),
          outline: Color(0xff5c6156),
          outlineVariant: Color(0xff787c71),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xff2e312a),
          // inverseOnSurface: Color(4293980903),
          inversePrimary: Color(0xffacd28f),
          primaryFixed: Color(0xff5c7e44),
          onPrimaryFixed: Color(0xffffffff),
          primaryFixedDim: Color(0xff44652e),
          onPrimaryFixedVariant: Color(0xffffffff),
          secondaryFixed: Color(0xff6c7960),
          onSecondaryFixed: Color(0xffffffff),
          secondaryFixedDim: Color(0xff536049),
          onSecondaryFixedVariant: Color(0xffffffff),
          tertiaryFixed: Color(0xff4f7c7c),
          onTertiaryFixed: Color(0xffffffff),
          tertiaryFixedDim: Color(0xff356363),
          onTertiaryFixedVariant: Color(0xffffffff),
          surfaceDim: Color(0xffd9dbd1),
          surfaceBright: Color(0xfff9faf0),
          surfaceContainerLowest: Color(0xffffffff),
          surfaceContainerLow: Color(0xfff3f5ea),
          surfaceContainer: Color(0xffedefe4),
          surfaceContainerHigh: Color(0xffe7e9df),
          surfaceContainerHighest: Color(0xffe1e4d9),
        ));
  }

  static ThemeData lightHighContrastScheme() {
    return ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xff0e2800),
          surfaceTint: Color(0xff476730),
          onPrimary: Color(0xffffffff),
          primaryContainer: Color(0xff2c4b17),
          onPrimaryContainer: Color(0xffffffff),
          secondary: Color(0xff1a2513),
          onSecondary: Color(0xffffffff),
          secondaryContainer: Color(0xff3b4631),
          onSecondaryContainer: Color(0xffffffff),
          tertiary: Color(0xff002727),
          onTertiary: Color(0xffffffff),
          tertiaryContainer: Color(0xff194a49),
          onTertiaryContainer: Color(0xffffffff),
          error: Color(0xff4e0002),
          onError: Color(0xffffffff),
          errorContainer: Color(0xff8c0009),
          onErrorContainer: Color(0xffffffff),
          surface: Color(0xfff9faf0),
          onSurface: Color(0xff000000),
          onSurfaceVariant: Color(0xff21251c),
          outline: Color(0xff40443a),
          outlineVariant: Color(0xff40443a),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xff2e312a),
          // inverseOnSurface: Color(4294967295),
          inversePrimary: Color(0xffd1f8b1),
          primaryFixed: Color(0xff2c4b17),
          onPrimaryFixed: Color(0xffffffff),
          primaryFixedDim: Color(0xff163302),
          onPrimaryFixedVariant: Color(0xffffffff),
          secondaryFixed: Color(0xff3b4631),
          onSecondaryFixed: Color(0xffffffff),
          secondaryFixedDim: Color(0xff25301c),
          onSecondaryFixedVariant: Color(0xffffffff),
          tertiaryFixed: Color(0xff194a49),
          onTertiaryFixed: Color(0xffffffff),
          tertiaryFixedDim: Color(0xff003333),
          onTertiaryFixedVariant: Color(0xffffffff),
          surfaceDim: Color(0xffd9dbd1),
          surfaceBright: Color(0xfff9faf0),
          surfaceContainerLowest: Color(0xffffffff),
          surfaceContainerLow: Color(0xfff3f5ea),
          surfaceContainer: Color(0xffedefe4),
          surfaceContainerHigh: Color(0xffe7e9df),
          surfaceContainerHighest: Color(0xffe1e4d9),
        ));
  }

  static ThemeData darkScheme() {
    return ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.dark,
          primary: Color(0xffacd28f),
          surfaceTint: Color(0xffacd28f),
          onPrimary: Color(0xff1a3705),
          primaryContainer: Color(0xff304f1a),
          onPrimaryContainer: Color(0xffc7eea9),
          secondary: Color(0xffbdcbaf),
          onSecondary: Color(0xff283420),
          secondaryContainer: Color(0xff3f4a35),
          onSecondaryContainer: Color(0xffd9e7ca),
          tertiary: Color(0xffa0cfce),
          onTertiary: Color(0xff003737),
          tertiaryContainer: Color(0xff1e4e4d),
          onTertiaryContainer: Color(0xffbbecea),
          error: Color(0xffffb4ab),
          onError: Color(0xff690005),
          errorContainer: Color(0xff93000a),
          onErrorContainer: Color(0xffffdad6),
          surface: Color(0xff11140e),
          onSurface: Color(0xffe1e4d9),
          onSurfaceVariant: Color(0xffc4c8bb),
          outline: Color(0xff8e9286),
          outlineVariant: Color(0xff44483e),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xffe1e4d9),
          // inverseOnSurface: Color(4281217322),
          inversePrimary: Color(0xff476730),
          primaryFixed: Color(0xffc7eea9),
          onPrimaryFixed: Color(0xff0a2000),
          primaryFixedDim: Color(0xffacd28f),
          onPrimaryFixedVariant: Color(0xff304f1a),
          secondaryFixed: Color(0xffd9e7ca),
          onSecondaryFixed: Color(0xff141e0c),
          secondaryFixedDim: Color(0xffbdcbaf),
          onSecondaryFixedVariant: Color(0xff3f4a35),
          tertiaryFixed: Color(0xffbbecea),
          onTertiaryFixed: Color(0xff002020),
          tertiaryFixedDim: Color(0xffa0cfce),
          onTertiaryFixedVariant: Color(0xff1e4e4d),
          surfaceDim: Color(0xff11140e),
          surfaceBright: Color(0xff373a33),
          surfaceContainerLowest: Color(0xff0c0f09),
          surfaceContainerLow: Color(0xff191d16),
          surfaceContainer: Color(0xff1d211a),
          surfaceContainerHigh: Color(0xff282b24),
          surfaceContainerHighest: Color(0xff33362f),
        ));
  }

  static ThemeData darkMediumContrastScheme() {
    return ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.dark,
          primary: Color(0xffb0d693),
          surfaceTint: Color(0xffacd28f),
          onPrimary: Color(0xff071b00),
          primaryContainer: Color(0xff779b5d),
          onPrimaryContainer: Color(0xff000000),
          secondary: Color(0xffc2cfb3),
          onSecondary: Color(0xff0f1908),
          secondaryContainer: Color(0xff88957b),
          onSecondaryContainer: Color(0xff000000),
          tertiary: Color(0xffa4d4d2),
          onTertiary: Color(0xff001a1a),
          tertiaryContainer: Color(0xff6b9998),
          onTertiaryContainer: Color(0xff000000),
          error: Color(0xffffbab1),
          onError: Color(0xff370001),
          errorContainer: Color(0xffff5449),
          onErrorContainer: Color(0xff000000),
          surface: Color(0xff11140e),
          onSurface: Color(0xfffafcf1),
          onSurfaceVariant: Color(0xffc8ccbf),
          outline: Color(0xffa0a598),
          outlineVariant: Color(0xff808579),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xffe1e4d9),
          // inverseOnSurface: Color(4280822564),
          inversePrimary: Color(0xff31501b),
          primaryFixed: Color(0xffc7eea9),
          onPrimaryFixed: Color(0xff051500),
          primaryFixedDim: Color(0xffacd28f),
          onPrimaryFixedVariant: Color(0xff1f3d0a),
          secondaryFixed: Color(0xffd9e7ca),
          onSecondaryFixed: Color(0xff0a1404),
          secondaryFixedDim: Color(0xffbdcbaf),
          onSecondaryFixedVariant: Color(0xff2e3a25),
          tertiaryFixed: Color(0xffbbecea),
          onTertiaryFixed: Color(0xff001414),
          tertiaryFixedDim: Color(0xffa0cfce),
          onTertiaryFixedVariant: Color(0xff073d3d),
          surfaceDim: Color(0xff11140e),
          surfaceBright: Color(0xff373a33),
          surfaceContainerLowest: Color(0xff0c0f09),
          surfaceContainerLow: Color(0xff191d16),
          surfaceContainer: Color(0xff1d211a),
          surfaceContainerHigh: Color(0xff282b24),
          surfaceContainerHighest: Color(0xff33362f),
        ));
  }

  static ThemeData darkHighContrastScheme() {
    return ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.dark,
          primary: Color(0xfff3ffe3),
          surfaceTint: Color(0xffacd28f),
          onPrimary: Color(0xff000000),
          primaryContainer: Color(0xffb0d693),
          onPrimaryContainer: Color(0xff000000),
          secondary: Color(0xfff3ffe3),
          onSecondary: Color(0xff000000),
          secondaryContainer: Color(0xffc2cfb3),
          onSecondaryContainer: Color(0xff000000),
          tertiary: Color(0xffeafffe),
          onTertiary: Color(0xff000000),
          tertiaryContainer: Color(0xffa4d4d2),
          onTertiaryContainer: Color(0xff000000),
          error: Color(0xfffff9f9),
          onError: Color(0xff000000),
          errorContainer: Color(0xffffbab1),
          onErrorContainer: Color(0xff000000),
          surface: Color(0xff11140e),
          onSurface: Color(0xffffffff),
          onSurfaceVariant: Color(0xfff8fcee),
          outline: Color(0xffc8ccbf),
          outlineVariant: Color(0xffc8ccbf),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xffe1e4d9),
          // inverseOnSurface: Color(4278190080),
          inversePrimary: Color(0xff133101),
          primaryFixed: Color(0xffccf3ad),
          onPrimaryFixed: Color(0xff000000),
          primaryFixedDim: Color(0xffb0d693),
          onPrimaryFixedVariant: Color(0xff071b00),
          secondaryFixed: Color(0xffdeebce),
          onSecondaryFixed: Color(0xff000000),
          secondaryFixedDim: Color(0xffc2cfb3),
          onSecondaryFixedVariant: Color(0xff0f1908),
          tertiaryFixed: Color(0xffc0f0ef),
          onTertiaryFixed: Color(0xff000000),
          tertiaryFixedDim: Color(0xffa4d4d2),
          onTertiaryFixedVariant: Color(0xff001a1a),
          surfaceDim: Color(0xff11140e),
          surfaceBright: Color(0xff373a33),
          surfaceContainerLowest: Color(0xff0c0f09),
          surfaceContainerLow: Color(0xff191d16),
          surfaceContainer: Color(0xff1d211a),
          surfaceContainerHigh: Color(0xff282b24),
          surfaceContainerHighest: Color(0xff33362f),
        ));
  }
}
